const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let replay=null,replayIndex=0,replayStart=0,replayWindow=0,replayTimer=null,replayPlaying=true;
const colors=['#ef5350','#53b9ff','#f5d44d','#89938e'];
function boardSVG(bytes){let cells='';for(let i=0;i<128;i++){let v=bytes[i]||0;if(!v)continue;let x=i%8,y=Math.floor(i/8),c=colors[v&3],virus=(v&0xf0)===0xd0;cells+=virus?`<circle class="cell-virus" cx="${x+.5}" cy="${y+.5}" r=".39" fill="${c}"/><circle cx="${x+.38}" cy="${y+.43}" r=".07" fill="#09110e"/><circle cx="${x+.62}" cy="${y+.43}" r=".07" fill="#09110e"/>`:`<rect x="${x+.08}" y="${y+.08}" width=".84" height=".84" rx=".3" fill="${c}"/>`;}return `<svg class="bottle-svg" viewBox="-.5 -.8 9 17.3"><path d="M0 0v15.8h8V0M0 0h2.7v-.6h2.6V0H8" fill="#0b1511" stroke="#789187" stroke-width=".14"/>${cells}</svg>`}
function drawReplay(){if(!replay?.replay?.length)return;let f=replay.replay[replayIndex%replay.replay.length];document.querySelector('#bottle-a').innerHTML=boardSVG(f.boards[0]);document.querySelector('#bottle-b').innerHTML=boardSVG(f.boards[1]);document.querySelector('#replay-pos').textContent=`placement ${replayIndex+1} / ${replay.replay.length}`;}
function scheduleReplay(){clearTimeout(replayTimer);if(!replayPlaying||!replay)return;let speed=+document.querySelector('#replay-speed').value||4,ms=Math.max(90,(replay.match_len_sec/replay.replay.length)*1000/speed);replayTimer=setTimeout(()=>{replayIndex++;if(replayIndex>=replayStart+replayWindow)replayIndex=replayStart;drawReplay();scheduleReplay()},ms)}
async function loadReplay(id,by){replay=await fetch(`/api/replay/${id}`).then(r=>r.json());replayWindow=Math.min(160,replay.replay.length);replayStart=Math.floor(Math.random()*Math.max(1,replay.replay.length-replayWindow));replayIndex=replayStart;document.querySelector('#replay-section').hidden=false;document.querySelector('#replay-title').textContent=`${by[replay.agent_a]?.name||replay.agent_a} vs ${by[replay.agent_b]?.name||replay.agent_b} · random excerpt`;drawReplay();scheduleReplay()}
function speedChart(points){if(!points?.length)return '';let vals=points.map(p=>+p[1]),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;return `<polyline fill="none" stroke="#b9ef63" stroke-width="4" vector-effect="non-scaling-stroke" points="${vals.map((v,i)=>`${i/(vals.length-1||1)*1000},${140-(v-lo)/span*125}`).join(' ')}"/>`}
async function refresh(){const d=await fetch('/api/snapshot').then(r=>r.json());const by=Object.fromEntries(d.agents.map(a=>[a.id,a]));
 document.querySelector('#games').textContent=`${d.games.toLocaleString()} games`;document.querySelector('#updated').textContent=new Date(d.generated).toLocaleTimeString();
 const champ=d.agents.find(a=>a.status==='champion'),leader=champ||d.agents.find(a=>a.games>0);document.querySelector('#leader-label').textContent=champ?'Current champion':'Provisional leader';document.querySelector('#champion').textContent=leader?.name||'Waiting for games';document.querySelector('#champion-meta').textContent=leader?`${leader.family} · generation ${leader.generation} · ${leader.games} rated games${champ?'':' · no champion crowned'}`:'Play connected matchups to establish the field.';
 const t=d.training||{},m=t.latest||{};document.querySelector('#training-run').textContent=t.run||'waiting for metrics';document.querySelector('#fps').textContent=m['perf/sps']?Math.round(m['perf/sps']).toLocaleString():'—';document.querySelector('#dps').textContent=m['perf/dps']?Math.round(m['perf/dps']).toLocaleString():'—';document.querySelector('#search-cover').textContent=m['search_distill/searched_fraction_actual']!=null?`${(m['search_distill/searched_fraction_actual']*100).toFixed(1)}%`:'off';document.querySelector('#update-sec').textContent=m['perf/update_sec']!=null?`${m['perf/update_sec'].toFixed(2)}s`:'—';document.querySelector('#speed-chart').innerHTML=speedChart(t.history?.['perf/sps']);
 document.querySelector('#ratings').innerHTML=d.agents.map((a,i)=>`<tr><td>${i+1}</td><td><span class="entrant">${esc(a.name)}</span><span class="sub">${esc(a.id)}</span></td><td>${esc(a.family)} · G${a.generation}</td><td><span class="badge ${a.status}">${a.status}</span></td><td class="rating">${a.rating==null?'unrated':`${a.rating>0?'+':''}${a.rating}`}</td><td>${a.rating95==null?'—':`±${a.rating95}`}</td><td>${a.wins}</td><td>${a.losses}</td><td>${a.draws}</td><td>${a.clears}</td><td>${a.topouts}</td><td>${a.games}</td></tr>`).join('');
 document.querySelector('#matches').innerHTML=d.recent.slice(0,12).map(m=>{let A=by[m.agent_a]?.name||m.agent_a,B=by[m.agent_b]?.name||m.agent_b,w=m.winner==='a'?A:m.winner==='b'?B:'draw';return `<div class="card ${m.has_replay?'replay-link':''}" ${m.has_replay?`data-replay="${m.id}"`:''}><span>${esc(A)}</span><b class="score">${esc(w)}${m.has_replay?' · ▶':''}</b><span>${esc(B)}</span></div>`}).join('')||'<p class="event">No matches yet.</p>';
 document.querySelector('#events').innerHTML=d.events.slice(0,12).map(e=>`<div class="event"><time>${new Date(e.created).toLocaleDateString()}</time><span><b>${esc(e.kind)}</b> · ${esc(by[e.agent_id]?.name||e.agent_id||'arena')}</span></div>`).join('');
 document.querySelector('#matches').onclick=e=>{let row=e.target.closest('[data-replay]');if(row)loadReplay(row.dataset.replay,by).catch(console.error)};
 if(!replay){let sample=d.recent.filter(m=>m.has_replay);if(sample.length)loadReplay(sample[Math.floor(Math.random()*sample.length)].id,by).catch(console.error)}}
document.querySelector('#replay-toggle').onclick=e=>{replayPlaying=!replayPlaying;e.target.textContent=replayPlaying?'Pause':'Play';scheduleReplay()};document.querySelector('#replay-speed').onchange=scheduleReplay;
refresh().catch(console.error);setInterval(()=>refresh().catch(console.error),5000);
