const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let replay=null,replayIndex=0,replayTimer=null,replayPlaying=true,replayRequest=0;
const colors=['#f5d44d','#ef5350','#53b9ff','#89938e'];
function boardSVG(bytes,pill){let cells='';for(let i=0;i<128;i++){let v=bytes[i]||0;if(!v||v===255||(v&0xf0)===0xf0||(v&0xf0)===0xb0)continue;let x=i%8,y=Math.floor(i/8),c=colors[v&3],virus=(v&0xf0)===0xd0;cells+=virus?`<circle class="cell-virus" cx="${x+.5}" cy="${y+.5}" r=".39" fill="${c}"/><circle cx="${x+.38}" cy="${y+.43}" r=".07" fill="#09110e"/><circle cx="${x+.62}" cy="${y+.43}" r=".07" fill="#09110e"/>`:`<rect x="${x+.08}" y="${y+.08}" width=".84" height=".84" rx=".3" fill="${c}"/>`;}cells+=fallingSVG(pill);return `<svg class="bottle-svg" viewBox="-.5 -.8 9 17.3"><path d="M0 0v15.8h8V0M0 0h2.7v-.6h2.6V0H8" fill="#0b1511" stroke="#789187" stroke-width=".14"/>${cells}</svg>`}
function drawReplay(){
 if(!replay?.replay?.length)return;
 const f=replay.replay[replayIndex];
 document.querySelector('#bottle-a').innerHTML=boardSVG(f.boards[0],f.pills?.[0]);
 document.querySelector('#bottle-b').innerHTML=boardSVG(f.boards[1],f.pills?.[1]);
 document.querySelector('#replay-pos').textContent=`snapshot ${replayIndex+1} / ${replay.replay.length}${Number.isFinite(f.frame)?` · ${(f.frame/60.0988).toFixed(2)}s`:''}`;
 document.querySelector('#replay-seek').value=replayIndex;
 document.querySelector('#replay-detail').textContent=f.note||'Recorded board snapshots; these do not show every controller input.';
}
function scheduleReplay(){
 cancelAnimationFrame(replayTimer);
 if(!replayPlaying||!replay?.replay?.length)return;
 if(replayIndex>=replay.replay.length-1){replayPlaying=false;document.querySelector('#replay-toggle').textContent='Play';return;}
 const speed=+document.querySelector('#replay-speed').value||4;
 const at=i=>Number.isFinite(replay.replay[i].frame)?replay.replay[i].frame/60.0988:i*replay.match_len_sec/replay.replay.length;
 const origin=at(replayIndex), started=performance.now();
 const tick=now=>{
   const target=origin+(now-started)*speed/1000, previous=replayIndex;
   while(replayIndex+1<replay.replay.length&&at(replayIndex+1)<=target)replayIndex++;
   if(previous!==replayIndex)drawReplay();
   if(replayIndex===replay.replay.length-1){replayPlaying=false;document.querySelector('#replay-toggle').textContent='Play';return;}
   replayTimer=requestAnimationFrame(tick);
 };
 replayTimer=requestAnimationFrame(tick);
}
async function loadReplay(id,by){
 const request=++replayRequest;
 const response=await fetch(`/api/replay/${id}`);
 if(!response.ok)throw Error(`Replay HTTP ${response.status}`);
 const loaded=await response.json();
 if(request!==replayRequest)return;
 if(!loaded.replay?.length)throw Error('Replay has no snapshots');
 replay=loaded;replay.id=String(id);replayIndex=0;
 document.querySelector('#replay-picker').value=String(id);
 document.querySelector('#replay-section').hidden=false;
 document.querySelector('#replay-title').textContent=`${by[replay.agent_a]?.name||replay.agent_a} vs ${by[replay.agent_b]?.name||replay.agent_b} · game ${replay.id} · L${replay.level ?? '?'} HI · seed ${replay.seed}`;
 document.querySelector('#replay-seek').max=replay.replay.length-1;
 drawReplay();scheduleReplay();
}
function speedChart(points){if(!points?.length)return '';let vals=points.map(p=>+p[1]),lo=Math.min(...vals),hi=Math.max(...vals),span=hi-lo||1;return `<polyline fill="none" stroke="#b9ef63" stroke-width="4" vector-effect="non-scaling-stroke" points="${vals.map((v,i)=>`${i/(vals.length-1||1)*1000},${140-(v-lo)/span*125}`).join(' ')}"/>`}
function workerHost(worker){let key=(worker.worker_id||'unknown').split('-')[0].toLowerCase();return key==='mac'?'Mac':key==='green'?'Green':key[0]?.toUpperCase()+key.slice(1)||'Unknown'}
function hostSummaries(workers){let groups=new Map;for(let worker of workers){let host=workerHost(worker),group=groups.get(host)||{host,workers:[],frames_per_sec:0,decisions_per_sec:0,games_per_min:0,games:0,simulated_frames:0,wall_seconds:0};group.workers.push(worker);group.frames_per_sec+=worker.frames_per_sec;group.decisions_per_sec+=worker.decisions_per_sec;group.games_per_min+=worker.games_per_min;group.games+=worker.games;group.simulated_frames+=worker.frames_per_game*worker.games;group.wall_seconds=Math.max(group.wall_seconds,worker.wall_seconds);groups.set(host,group)}return [...groups.values()].map(group=>{let devices=new Map;for(let worker of group.workers){let device=worker.device.toUpperCase(),summary=devices.get(device)||{count:0,threads:0,batches:new Set};summary.count++;summary.threads+=worker.threads;summary.batches.add(worker.batch_size);devices.set(device,summary)}group.configuration=[...devices].map(([device,x])=>`${x.count}× ${device} · ${x.threads} threads · batch ${[...x.batches].join('/')}`).join(' + ');group.frames_per_game=group.games?group.simulated_frames/group.games:0;return group}).sort((a,b)=>a.host.localeCompare(b.host))}
async function refresh(){const d=await fetch('/api/snapshot').then(r=>r.json());const by=Object.fromEntries(d.agents.map(a=>[a.id,a])),visibleAgents=d.agents.filter(a=>a.status!=='retired');
 const recorded=d.recorded_matches||[], picker=document.querySelector('#replay-picker');
 const archiveKey=JSON.stringify(recorded);
 if(picker.dataset.archive!==archiveKey){
   const selection=replay?.id||picker.value;
   picker.innerHTML='<option value="">Choose a recorded match</option>'+recorded.map(m=>`<option value="${m.id}">${esc(by[m.agent_a]?.name||m.agent_a)} vs ${esc(by[m.agent_b]?.name||m.agent_b)} · game ${m.id} · L${m.level} · seed ${m.seed} · ${esc(m.terminal_reason)}</option>`).join('');
   picker.value=selection;picker.dataset.archive=archiveKey;
 }
 picker.onchange=()=>{if(picker.value)loadReplay(picker.value,by).catch(console.error)};
 if(!replay&&recorded.length)loadReplay(recorded[0].id,by).catch(console.error);
 document.querySelector('#games').textContent=`${d.games.toLocaleString()} games`;document.querySelector('#updated').textContent=new Date(d.generated).toLocaleTimeString();
 const ratingFit=d.ratings||{},ratingDiag=ratingFit.diagnostics||{},live=ratingFit.method==='laplace',quality=live?`local Gaussian · mode gradient ${(+ratingDiag.mode_gradient_max||0).toExponential(1)}`:`R̂ ${ratingDiag.max_rhat?.toFixed(3)??'—'} · ESS ${Math.round(ratingDiag.min_ess??0).toLocaleString()}`,ratingState=ratingFit.status==='pending'?'posterior fit pending':`${ratingFit.status==='updating'?`${ratingFit.pending_games} new games pending · `:''}${live?'live Bayesian W/D/L':'audited Bayesian W/D/L'} · ${quality}`;document.querySelector('#ratings-status').textContent=`${ratingState} · active roster; historical evidence retained`;
 const champ=visibleAgents.find(a=>a.status==='champion'),leader=champ||visibleAgents.find(a=>a.games>0);document.querySelector('#leader-label').textContent=champ?'Current champion':'Provisional leader';document.querySelector('#champion').textContent=leader?.name||'Waiting for games';document.querySelector('#champion-meta').textContent=leader?`${leader.family} · generation ${leader.generation} · ${leader.games} rated games${champ?'':' · no champion crowned'}`:'Play connected matchups to establish the field.';
 const t=d.training||{},m=t.latest||{},outcomeRun=m['vs/win_rate']!=null,primaryKey=outcomeRun?'vs/win_rate':'validation/top1',lossKey=m['loss/total']!=null?'loss/total':'train/loss',trainingStep=m['global_step'];document.querySelector('#training-run').textContent=t.run||'waiting for metrics';document.querySelector('#training-steps').textContent=trainingStep!=null?(+trainingStep).toLocaleString():'—';document.querySelector('#training-steps').title=trainingStep!=null?`Exact absolute training step: ${trainingStep}`:'';document.querySelector('#fps').textContent=m['perf/sps']?Math.round(m['perf/sps']).toLocaleString():'—';document.querySelector('#dps').textContent=m['perf/dps']?Math.round(m['perf/dps']).toLocaleString():'—';document.querySelector('#primary-label').textContent=outcomeRun?'Rolling win rate':'Validation top-1';document.querySelector('#primary-signal').textContent=m[primaryKey]!=null?`${(100*m[primaryKey]).toFixed(1)}%`:'pending';document.querySelector('#loss-label').textContent=outcomeRun?'PPO total loss':'Train loss';document.querySelector('#train-loss').textContent=m[lossKey]!=null?(+m[lossKey]).toFixed(3):'—';document.querySelector('#speed-chart').innerHTML=speedChart(t.history?.['perf/sps']||t.tasks?.find(x=>x.history?.['perf/dps'])?.history?.['perf/dps']);
 document.querySelector('#training-tasks').innerHTML=(t.tasks||[]).map(x=>{let q=x.latest||{},pct=k=>q[k]==null?'—':`${(100*q[k]).toFixed(1)}%`,num=(k,n=3)=>q[k]==null?'—':(+q[k]).toFixed(n),rate=q['perf/sps']||q['perf/dps'],outcome=q['vs/win_rate']!=null,step=q['global_step']??q['vs/matches_total'],progress=q['train/epoch']?`epoch ${q['train/epoch']} · step ${(+q['train/step']).toLocaleString()}`:step!=null?`${q['global_step']!=null?'step':'matches'} ${(+step).toLocaleString()}`:'running',loss=num(q['loss/total']!=null?'loss/total':'train/loss'),primary=outcome?pct('vs/win_rate'):pct('validation/top1'),secondary=outcome?pct('vs/draw_rate'):num('validation/outcome_brier',4),tertiary=outcome?num('train/return_mean'):num('validation/mean_regret'),signal=q['validation/quality_top1']!=null?`quality top-1 ${pct('validation/quality_top1')}`:q['validation/regret_tail_gap']!=null?`tail gap ${num('validation/regret_tail_gap')}`:q['validation/objective']!=null?`objective ${num('validation/objective')}`:outcome?`clear ${pct('vs/clear_win_rate')} · league ${pct('vs/league_win_rate')} · ${(+q['vs/matches_total']).toLocaleString()} matches`:'learning';return `<tr><td><span class="entrant">${esc(x.run.split('/')[0])}</span><span class="sub">${esc(x.host||'remote')} · ${esc(x.run)}</span></td><td>${rate?Math.round(rate).toLocaleString():'—'}<span class="sub">${q['perf/sps']?'frames/s':'decisions/s'}</span></td><td>${esc(progress)}</td><td>${loss}</td><td>${primary}</td><td>${secondary}</td><td>${tertiary}</td><td>${esc(signal)}</td></tr>`}).join('');
 const workers=d.workers||[],hosts=hostSummaries(workers),arenaFps=workers.reduce((n,w)=>n+w.frames_per_sec,0),arenaDps=workers.reduce((n,w)=>n+w.decisions_per_sec,0);document.querySelector('#worker-status').textContent=workers.length?`${Math.round(arenaFps).toLocaleString()} simulated frames/s aggregate · ${Math.round(arenaDps).toLocaleString()} decisions/s · ${hosts.length} host${hosts.length===1?'':'s'} · ${workers.length} processes · trailing two minutes`:'waiting for instrumented worker samples';document.querySelector('#arena-workers').innerHTML=hosts.map(h=>`<tr><td><span class="entrant">${esc(h.host)}</span><span class="sub">${h.workers.length} live process${h.workers.length===1?'':'es'}</span></td><td>${esc(h.configuration)}</td><td>${Math.round(h.frames_per_sec).toLocaleString()}<span class="sub">${(h.frames_per_sec*60/1e6).toFixed(2)}M frames/min</span></td><td>${h.decisions_per_sec.toFixed(1)}</td><td>${h.games_per_min.toFixed(1)}</td><td>${Math.round(h.frames_per_game).toLocaleString()}</td><td>${h.games.toLocaleString()} games<span class="sub">${h.wall_seconds.toFixed(1)}s maximum sample window</span></td></tr>`).join('')||'<tr><td colspan="7">A host will appear after one of its workers finishes a batch.</td></tr>';
 document.querySelector('#ratings').innerHTML=visibleAgents.map((a,i)=>{let pct=n=>a.games?`${(100*n/a.games).toFixed(1)}%`:'—',signed=n=>`${n>0?'+':''}${n}`,next=visibleAgents[i+1],losNext=next?d.superiority?.[a.id]?.[next.id]:null,parent=by[a.parent_id];return `<tr><td><i class="status-dot ${a.status}" title="${esc(a.status)}"></i></td><td>${i+1}</td><td><span class="entrant" title="${esc(a.id)}">${esc(a.name)}</span></td><td>${esc(a.family)} · G${a.generation}</td><td>${a.games.toLocaleString()}</td><td class="rating">${a.rating==null?'unrated':signed(a.rating)}</td><td>${a.rating_low==null?'—':`${signed(a.rating_low)}…${signed(a.rating_high)}`}</td><td class="los-next" title="${next?`vs ${esc(next.name)}`:''}">${losNext==null?'—':`↓ ${(100*losNext).toFixed(1)}%`}</td><td class="los-parent" title="${parent?`vs ${esc(parent.name)}`:''}">${a.lineage_los==null?'—':`↳ ${(100*a.lineage_los).toFixed(1)}%`}</td><td>${a.probability_best==null?'—':`${(100*a.probability_best).toFixed(1)}%`}</td><td>${a.rank_low==null?'—':`${Math.round(a.rank_low)}…${Math.round(a.rank_high)}`}</td><td>${pct(a.wins)}</td><td>${pct(a.losses)}</td><td>${pct(a.draws)}</td><td>${pct(a.clears)}</td><td>${pct(a.topouts)}</td></tr>`}).join('');
 const scheduler=d.scheduler||{},scheduled=scheduler.matchups||[],boost=scheduler.new_entry_boost||{};document.querySelector('#scheduler-status').textContent=scheduler.mode==='bayesian_information'?`${scheduler.eligible_agents} focused entrants · ${scheduler.eligible_pairs} pairs · information softened by T=${scheduler.temperature??'—'} · ${100*(scheduler.coverage_mix??0)}% uniform coverage`:'building the comparison graph before Bayesian scheduling';document.querySelector('#scheduler').innerHTML=scheduled.map((x,i)=>{let A=by[x.a]?.name||x.a,B=by[x.b]?.name||x.b,factors=(x.factors||[]).map(f=>`<span class="factor ${f.display_only?'':f.factor>1?'boost':f.factor&&f.factor<1?'cost':''}">${esc(f.label)}${f.factor==null?'':` ×${f.factor}`}</span>`).join('')||'<span class="sub">information only</span>';return `<tr><td><span class="entrant">${i+1}. ${esc(A)} × ${esc(B)}</span></td><td class="schedule-share">${(100*x.selection_probability).toFixed(1)}%</td><td>${x.information_bits==null?'pending':`${(1000*x.information_bits).toFixed(2)} millibits`}<span class="sub">per completed game</span></td><td>${x.games.toLocaleString()}</td><td>${factors}</td></tr>`}).join('')||'<tr><td colspan="5">Waiting for at least two active entrants.</td></tr>';
 document.querySelector('#matches').innerHTML=d.recent.slice(0,12).map(m=>{let A=by[m.agent_a]?.name||m.agent_a,B=by[m.agent_b]?.name||m.agent_b,w=m.winner==='a'?A:m.winner==='b'?B:'draw';return `<div class="card ${m.has_replay?'replay-link':''}" ${m.has_replay?`data-replay="${m.id}"`:''}><span>${esc(A)}</span><b class="score">${esc(w)}${m.has_replay?' · ▶':''}</b><span>${esc(B)}</span></div>`}).join('')||'<p class="event">No matches yet.</p>';
 document.querySelector('#events').innerHTML=d.events.slice(0,12).map(e=>`<div class="event"><time>${new Date(e.created).toLocaleDateString()}</time><span><b>${esc(e.kind)}</b> · ${esc(by[e.agent_id]?.name||e.agent_id||'arena')}</span></div>`).join('');
 document.querySelector('#matches').onclick=e=>{let row=e.target.closest('[data-replay]');if(row)loadReplay(row.dataset.replay,by).catch(console.error)};
 if(!replay&&!recorded.length){let sample=d.recent.filter(m=>m.has_replay);if(sample.length)loadReplay(sample[0].id,by).catch(console.error)}}
document.querySelector('#replay-toggle').onclick=e=>{replayPlaying=!replayPlaying;if(replayPlaying&&replayIndex===replay?.replay.length-1){replayIndex=0;drawReplay()}e.target.textContent=replayPlaying?'Pause':'Play';scheduleReplay()};document.querySelector('#replay-speed').onchange=scheduleReplay;
function seekReplay(index){if(!replay)return;replayPlaying=false;cancelAnimationFrame(replayTimer);document.querySelector('#replay-toggle').textContent='Play';replayIndex=Math.max(0,Math.min(replay.replay.length-1,index));drawReplay()}
document.querySelector('#replay-seek').oninput=e=>seekReplay(+e.target.value);
document.querySelector('#replay-prev').onclick=()=>seekReplay(replayIndex-1);
document.querySelector('#replay-next').onclick=()=>seekReplay(replayIndex+1);
async function pollArena(){try{await refresh();document.querySelector('#connection-status').textContent='CONNECTED';document.querySelector('#connection-dot').classList.remove('stale')}catch(error){document.querySelector('#connection-status').textContent='RECONNECTING';document.querySelector('#connection-dot').classList.add('stale');console.error(error)}finally{setTimeout(pollArena,5000)}}
pollArena();

function fallingSVG(pill){if(!Array.isArray(pill)||pill.length!==5)return "";const [x,y,r,a,b]=pill;if(!Number.isInteger(r)||r<0||r>3)return "";const dx=[[0,1],[0,0],[1,0],[0,0]][r],dy=[[0,0],[0,-1],[0,0],[-1,0]][r];return [a,b].map((c,i)=>`<rect x="${x+dx[i]+.06}" y="${y+dy[i]+.06}" width=".88" height=".88" rx=".28" fill="${colors[c&3]}" stroke="#fff" stroke-width=".05"/>`).join("")}
