name: drmario_pixel_baseline
algo: PPO
num_workers: 8
num_envs_per_worker: 32
rollout: 128
batch_size: 32768
lr: 0.0003
gamma: 0.997
gae_lambda: 0.95
entropy_coef: 0.003
frame_skip: 1
obs_mode: pixel
grayscale: false
resize: [128, 128]
use_lstm: true
risk_conditioning: true
env_id: DrMarioRetroEnv
max_steps: 10000000
log_interval: 2000
save_interval: 200000
