# Sample Factory 2.x style config (illustrative; adjust to your SF version)
# Launch with: python training/run_sf.py --cfg training/sf_configs/state_baseline_sf2.yaml

algo: APPO
env: DrMarioRetroEnv-v0
experiment: drmario_state_v0

# Parallelism
num_workers: 8
num_envs_per_worker: 32
rollout: 128

# PPO-ish
gamma: 0.997
gae_lambda: 0.95
ppo_clip_ratio: 0.2
entropy_coef: 0.003
learning_rate: 0.0003

# Observations
obs_mode: state
frame_stack: 4

# Risk conditioning
risk_tau_train_low: 0.25
risk_tau_train_high: 0.75

# Logging/checkpoints
with_wandb: false
save_every_sec: 600

