"""Check whether frozen source outcomes reproduce under the current adapter.

This is an exact-reserve replay diagnostic, not a public counterfactual label
producer. The recorded root action is forced once, then both sides use the
frozen ensemble argmax. Private snapshot bytes remain inside the native engine.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import time
from collections import defaultdict
from pathlib import Path

import numpy as np

from drmc_rl.envs.backends.drmario_vs_pool import DrMarioVsPoolRunner
from drmc_rl.search.native_pair import capture_native_state, state_from_payload
from drmc_rl.search.strong_league import FrozenStrongLeagueMixture
from drmc_rl.search.strong_league_memberwise import read_davidson_calibration, read_mixture_members
from drmc_rl.teachers.counterfactual_release import canonical_json, sha256_file
from drmc_rl.teachers.v3_baseline import load_source_rows

OUTCOMES = {1: "win", 2: "loss", 3: "draw"}


def select_rows(
    rows,
    count,
    seed,
    *,
    stratum_fields=("level", "speed", "tactical_stratum"),
    allowed_policies=("frozen-strong-league-mixture-argmax",),
):
    """Stable tactical round robin, at most one position from each whole game."""
    cells = defaultdict(list)
    seen = set()
    for row in rows:
        if row["id"] in seen:
            raise ValueError("source IDs must be unique")
        seen.add(row["id"])
        if not row.get("natural_outcome_available") or row.get("outcome") not in OUTCOMES.values():
            continue
        if row.get("rollout_policy") not in allowed_policies:
            raise ValueError("source was not generated by the frozen ensemble argmax")
        key = tuple(str(row[k]) for k in stratum_fields)
        cells[key].append(row)
    for values in cells.values():
        values.sort(key=lambda r: hashlib.sha256(f"{seed}:{r['id']}".encode()).digest())
    selected, games = [], set()
    while len(selected) < count:
        added = False
        for key in sorted(cells):
            while cells[key] and cells[key][-1]["game_id"] in games:
                cells[key].pop()
            if cells[key]:
                row = cells[key].pop()
                selected.append(row)
                games.add(row["game_id"])
                added = True
                if len(selected) == count:
                    break
        if not added:
            break
    if len(selected) != count:
        raise ValueError(f"only {len(selected)} independent eligible games for {count} requested")
    return selected


def choose_action(prediction, legal):
    if not legal:
        return -1
    probabilities, _value = prediction
    return int(max(legal, key=lambda action: probabilities.get(action, 1e-8)))


def replay_rows(rows, mixture, *, max_events, progress=None):
    runners = [DrMarioVsPoolRunner(num_pairs=1) for _ in rows]
    states = [state_from_payload(row) for row in rows]
    records = [{
        "source_id": row["id"], "game_id": row["game_id"],
        "stratum": [row[k] for k in ("level", "speed", "tactical_stratum")],
        "recorded_outcome": row["outcome"], "recorded_action": int(row["observed_action"]),
        "root_side": int(row["root_side"]), "initial_action_matches": None,
        "replayed_outcome": None, "outcome_matches": None, "events": 0,
    } for row in rows]
    complete = set()
    try:
        for runner, state in zip(runners, states, strict=True):
            runner.restore(0, state.privileged.engine_checkpoint)
            if runner.snapshot(0) != state.privileged.engine_checkpoint:
                raise RuntimeError("native restore changed the source checkpoint")
        for event in range(max_events):
            requests, destinations = [], []
            actions = [np.full(2, -2, dtype=np.int32) for _ in rows]
            for index, state in enumerate(states):
                if index in complete:
                    continue
                for side, need in enumerate(state.privileged.need_action):
                    if need:
                        if state.legal_actions_by_side[side]:
                            requests.append((state, side))
                            destinations.append((index, side))
                        else:
                            actions[index][side] = -1
            for (index, side), prediction in zip(destinations, mixture.infer_batch(requests), strict=True):
                legal = states[index].legal_actions_by_side[side]
                action = choose_action(prediction, legal)
                if event == 0 and side == records[index]["root_side"]:
                    observed = records[index]["recorded_action"]
                    if observed not in legal:
                        raise ValueError("recorded root action is not legal")
                    records[index]["initial_policy_action"] = action
                    records[index]["initial_action_matches"] = action == observed
                    action = observed
                actions[index][side] = action
            for index, (runner, action) in enumerate(zip(runners, actions, strict=True)):
                if index in complete:
                    continue
                runner.step_strict(action)
                if np.any(runner.buffers.invalid_action >= 0):
                    raise RuntimeError("replay rejected a complete-frontier action")
                previous = states[index]
                states[index] = capture_native_state(
                    runner,
                    level=previous.level,
                    speed_setting=previous.speed_setting,
                    viruses_initial=previous.viruses_initial,
                    previous=previous,
                )
                record = records[index]
                record["events"] = event+1
                outcome = OUTCOMES.get(states[index].privileged.terminal_outcome[record["root_side"]])
                if outcome is not None:
                    record["replayed_outcome"] = outcome
                    record["outcome_matches"] = outcome == record["recorded_outcome"]
                    complete.add(index)
                elif runner.buffers.truncated[0]:
                    complete.add(index)
            if progress is not None and (event+1) % 50 == 0:
                progress(event+1, len(complete), len(rows))
            if len(complete) == len(rows):
                break
    finally:
        for runner in runners:
            runner.close()
    if any(r["initial_action_matches"] is None for r in records):
        raise RuntimeError("source did not begin at its recorded root decision")
    return records


def summarize(records):
    terminal = [r for r in records if r["replayed_outcome"] is not None]
    return {
        "states": len(records), "games": len({r["game_id"] for r in records}),
        "initial_action_matches": sum(r["initial_action_matches"] for r in records),
        "natural_terminal": len(terminal), "incomplete": len(records)-len(terminal),
        "outcome_matches": sum(r["outcome_matches"] for r in terminal),
        "outcome_agreement": (sum(r["outcome_matches"] for r in terminal)/len(terminal)
                              if terminal else None),
        "mismatched_initial_but_same_outcome": sum(
            not r["initial_action_matches"] and r["outcome_matches"] for r in terminal),
    }


def main():
    import torch

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--state-bank", type=Path, required=True)
    parser.add_argument("--mixture-manifest", type=Path, required=True)
    parser.add_argument("--wdl-calibration", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--states", type=int, default=96)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--max-events", type=int, default=512)
    parser.add_argument("--seed", type=int, default=20260910)
    parser.add_argument("--device", default="cpu")
    args = parser.parse_args()
    if min(args.states, args.batch_size, args.max_events) < 1:
        parser.error("state, batch, and event counts must be positive")
    if args.output.exists():
        raise FileExistsError(args.output)
    torch.set_num_threads(2)
    rows = select_rows(load_source_rows(args.state_bank), args.states, args.seed)
    members = read_mixture_members(args.mixture_manifest)
    mixture = FrozenStrongLeagueMixture(
        members, read_davidson_calibration(args.wdl_calibration), device=args.device)
    records = []
    started = time.monotonic()
    for start in range(0, len(rows), args.batch_size):
        batch = rows[start:start+args.batch_size]
        records.extend(replay_rows(batch, mixture, max_events=args.max_events,
            progress=lambda event, done, total: print(
                f"batch {start}: event {event}; finished {done}/{total}", flush=True)))
        print(json.dumps(summarize(records)), flush=True)
    repo = Path(__file__).resolve().parents[1]
    strata = defaultdict(list)
    for record in records:
        strata["/".join(map(str, record["stratum"]))].append(record)
    report = {
        "schema": "drmc-rollout-consistency-audit-v1", "diagnostic_only": True,
        "product_gates_passed": False, "summary": summarize(records),
        "contract": "force-recorded-root-once-then-current-frozen-ensemble-argmax-v1",
        "information_scope": "privileged-exact-reserve-replay; not public counterfactual predictions",
        "selection": "one-state-per-game-stratified-hash-round-robin-v1",
        "seed": args.seed, "batch_size": args.batch_size, "max_events": args.max_events,
        "elapsed_seconds": time.monotonic()-started,
        "source_sha256": sha256_file(args.state_bank),
        "mixture_sha256": sha256_file(args.mixture_manifest),
        "calibration_sha256": sha256_file(args.wdl_calibration),
        "checkpoint_sha256": {member.id: member.sha256 for member in members},
        "selected_sources_sha256": hashlib.sha256(canonical_json([r["id"] for r in rows])).hexdigest(),
        "repository_commit": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo, text=True).strip(),
        "native_revision": subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=repo/"vendor/drmario_native", text=True).strip(),
        "source_code_sha256": {path: sha256_file(repo/path) for path in (
            "tools/audit_rollout_consistency.py", "drmc_rl/search/strong_league.py",
            "drmc_rl/search/native_pair.py", "drmc_rl/game/observation.py")},
        "strata": {key: summarize(value) for key, value in sorted(strata.items())},
        "records": records,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("x") as handle:
        handle.write(json.dumps(report, indent=2)+"\n")
    print(json.dumps({k: v for k, v in report.items() if k not in ("strata", "records")}, indent=2))


if __name__ == "__main__":
    main()
